### ISSUE TITLE
Issue with Windows 10

### ISSUE THREAD

**Issue by candideu** [juanitogan/slick#1]
![Capture](https://user-images.githubusercontent.com/55474996/83234652-a6767400-a15e-11ea-8dc7-fa65e857aafd.PNG)

Hello,

I am using Inkscape 1.0 (4035a4fb49, 2020-05-01) on a Windows 10 laptop and received this error message when I tried your extension.

**Comment by juanitogan** [comment]
Thank you for reporting this.  I haven't done any SVG work in a while so I wasn't aware that Inkscape 1.0 had _finally_ been released.  Yeah, I'm not surprised this broke in 1.0.  I had read that a ton of changes were coming with 1.0 and that it would break most extensions.

I don't have time to get to this today but I should be able to get this updated sometime this weekend.

**Comment by candideu** [comment]
> 
> 
> Thank you for reporting this. I haven't done any SVG work in a while so I wasn't aware that Inkscape 1.0 had _finally_ been released. Yeah, I'm not surprised this broke in 1.0. I had read that a ton of changes were coming with 1.0 and that it would break most extensions.
> 
> I don't have time to get to this today but I should be able to get this updated sometime this weekend.

Awesome, no rush! I was looking for hours for a good, up-to-date extension that could batch export layers (since their tool is malfunctioning), and this seemed like the perfect fit.

**Comment by juanitogan** [comment]
This has been fixed.  Technically, it was still working fine (except from the command line) but I've updated things to get rid of all the deprecation warning messages.
